### ISSUE TITLE
Unable to use in iOS App Extension due to sharedApplication

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gtm-http-fetcher#11]
```
What steps will reproduce the problem?

1. Create an iOS app and app extension using Xcode
2. Follow instructions to use Endpoints in iOS client: 
https://cloud.google.com/appengine/docs/python/endpoints/consume_ios
3. Include Google API Obj-C Client in app extension

What is the expected output? What do you see instead?

To be able to use the client / endpoints API inside an App Extension

Instead, I get the following error when trying to build:

GTMHTTPFetcher.m: 'sharedApplication' is unavailable: not available on iOS (App 
Extension) - Use view controller based solutions where appropriate instead.

What version of the product are you using? On what operating system?

Xcode: 6.1.1
iOS: 8
Mac: 10.10.1

Please provide any additional information below.

It works properly in the main app, just not in an app extensions

```

Original issue reported on code.google.com by `benjbea...@gmail.com` on 15 Jan 2015 at 11:43

**Comment by MuscleRumble** [comment]
Having the same issue here. Any idea on how to fix that?

**Comment by applesharethis** [comment]
How to write an articlePick something current?Use two independent sources?Read your sources before writing the story in your own words?. Do choose a unique title? before you start.Follow Wikinews' structure? for articles, answering as many of who what when where why and how? as you can; summarised in a short, two- or three-sentence opening paragraph. Once complete, your article must be three or more paragraphs.If you need help, you can add {{helpme}} to your talkpage, along with a question, or alternatively, just ask?Use this tab to enter your title and get a basic article template.[RECOMMENDED. Starts your article through the semi-automated {{develop}}—>{{review}}—>{{publish}} collaboration process.]
--
Welcome! Thank you for joining Wikinews; we'd love for you to stick around and get more involved. To help you get started we have an essay that will guide you through the process of writing your first full article. There are many other things you can do on the project, but its lifeblood is new, current, stories written neutrally.As you get more involved, you will need to look into key project policies and other discussions you can participate in; so, keep this message on this page and refer to the other links in it when you want to learn more, or have any problems.
