### ISSUE TITLE
does GTMHTTPFetcher support ipv6?

### ISSUE THREAD

**Issue by lionner** [google/gtm-http-fetcher#25]
does GTMHTTPFetcher support ipv6???

**Comment by thomasvl** [comment]
As mentioned in the README.md, `GTMHTTPFetcher` is a wrapper over `NSURLConnection`, so it gets what the system supports.

If your minimum supported OS version is iOS ≥ 7.0 or OS X ≥ 10.9, then Apple has moved to `NSURLSession`; https://github.com/google/gtm-session-fetcher provides a similar wrapper around that for easier use.
