### ISSUE TITLE
An SSL error has occurred and a secure connection to the server cannot be made. error is seen in iOS 10 devices.

### ISSUE THREAD

**Issue by mnang** [google/gtm-http-fetcher#27]
we're GTMHTTPFecther class in my project and it was working fine until iOS 9.3 version. After upgrade to iOS 10 we're seeing SSL connection issues and unable to fetch the data.
Is there anything i need to change in gtm-http-fecther class to support iOS 010?
this is the error we're seeing:
An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802).
We're using TLS1.0 on the server side with SHA-1 connection. I've added all the ATS exceptions to plist file but still no luck.
Any help would be appreciated.

**Comment by thomasvl** [comment]
Nothing immediately jumps to mind.  Aside: depending on what your min version supported is, you might want to switch to https://github.com/google/gtm-session-fetcher (but that likely will be some more work then you want at the moment).

Apple has been cranking up the SSL requirements, so it could be that using the iOS 10 sdk is requiring you have more explicit info.plist keys also to go with things.  So you might want to revisit Apple's release notes/docs about things like `NSAppTransportSecurity`.

**Comment by mnang** [comment]
I'm using new Xcode version 8.0 and the deployment target was set to 8.0 by default. I've changed to 6.0. Is that you mean by min version?
here is my ATS settings:

<key>NSAppTransportSecurity</key>
	<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    <key>NSExceptionDomains</key>
    <dict><key>hostname</key>
        <dict>
<key>NSIncludesSubdomains</key>
            rue/>
             <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
                </dict>
        </dict>
	</dict>

let me know if this is correct.

**Comment by mwyman** [comment]
Apple really discourages TLS < v1.2. If you can't update your server, you may need to add ATS keys such as NSExceptionMinimumTLSVersion (see: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

**Comment by mnang** [comment]
Thanks for the reply, but i've added the ATS to plist. 
Please see the details below:

<key>NSAppTransportSecurity</key>
	<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    <key>NSExceptionDomains</key>
       <dict>
 <key>hostname</key>
         <dict>
 <key>NSIncludesSubdomains</key>
            <true/>
 <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
            <true/>
  <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
<key>NSTemporaryExceptionMinimumTLSVersion</key>
            <string>TLSv1.1</string>
       </dict>
  </dict>
</dict>

Do i need to add any other details?

**Comment by mnang** [comment]
here is the screen shot for better understanding:
<img width="397" alt="screen shot 2016-09-27 at 6 38 43 pm" src="https://cloud.githubusercontent.com/assets/22328304/18894600/e933c862-84e1-11e6-89b8-045495d5efb3.png">

**Comment by thomasvl** [comment]
You mentioned TLS1.0 in the initial comment, but 1.1 in your last comment.  If you are 1.0, then the 1.1 value likely isn't enough, right?

**Comment by mnang** [comment]
I should mention as 1.0?

**Comment by thomasvl** [comment]
This issue being discussed here isn't about the Fetcher code, it is about your server and convincing the OS to allow you to talk to it.  If your server is TLS1.0, then (as I read it) requesting an exception for 1.1 isn't going to work.  You likely want to read up some of the linked docs and Apple's general iOS 10 notes about the added networking security they are doing/requiring.

**Comment by mnang** [comment]
I tried both 1.0 as well as 1.1, but none of them worked.

**Comment by thomasvl** [comment]
Closing this out since it looks like a site specific config and not something with the library itself.

**Comment by mvalbuquerque** [comment]
i have the same Problem
Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by ccassion** [comment]
@mvalbuquerque Late to the party but, were you able to resolve that issue? And how? I am trying to connect to firebase storage and its throwing that error on ios sims.
